### ISSUE TITLE
All Tags return "AI_Errored"

### ISSUE THREAD

**Issue by CheezusJeezus** [skier233/nsfw_ai_model_server#18]
These may just be first setup blues but I cannot seem to get this system to work. 
I call the script from stash and recieve the following

`2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] Failed to process video: ***************************************************************:8000/process_video/ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] Traceback (most recent call last): 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_tagger.py", line 249, in __tag_scene 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] server_result = await ai_server.process_video_async(video_path=mutated_path, vr_video=vr_video) 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_server.py", line 43, in process_video_async 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] return await post_api_async(session, 'process_video/', {"path": video_path, "frame_interval": frame_interval, "threshold": threshold, "return_confidence": return_confidence, "vr_video": vr_video}) 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_server.py", line 14, in post_api_async 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] async with session.post(url, json=payload) as response: 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] self._resp: _RetType = await self._coro 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^        
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 523, in _request 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] raise NonHttpUrlClientError(url) 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] aiohttp.client_exceptions.NonHttpUrlClientError: bd2818efb391c9c9b2a336cafa8c5d9068a40c40ec5c7c0fb247edf3b37c29b4:8000/process_video/ 
2024-11-04 00:58:13 stash  | ERRO[2024-11-04 06:58:13] [Plugin / AI Tagger] e                     
2024-11-04 00:58:13 stash  | 2024-11-04T06:58:13.991966324Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:44806","requestID":"05065a0ba10c/2igG81721z-002297","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://###.##.#.#:9999/graphql"} httpResponse={"bytes":67,"elapsed":5.473221,"status":200} service=stash
2024-11-04 00:58:14 stash  | 2024-11-04T06:58:14.001449522Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:44806","requestID":"05065a0ba10c/2igG81721z-002298","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://###.##.#.#:9999/graphql"} httpResponse={"bytes":67,"elapsed":6.270132,"status":200} service=stash
2024-11-04 00:58:19 stash  | 2024-11-04T06:58:19.019459438Z WRN Response: 404 Client Error httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002299","requestMethod":"GET","requestPath":"/scene/b0986f9558188b42_thumbs.vtt","requestURL":"http://localhost:9999/scene/b0986f9558188b42_thumbs.vtt"} httpResponse={"bytes":43,"elapsed":0.950539,"status":404} service=stash
2024-11-04 00:58:19 stash  | 2024-11-04T06:58:19.70106781Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002300","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://localhost:9999/graphql"} httpResponse={"bytes":2851,"elapsed":32.70801,"status":200} service=stash
2024-11-04 00:58:19 stash  | 2024-11-04T06:58:19.849613536Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002301","requestMethod":"GET","requestPath":"/scene/241/screenshot","requestURL":"http://localhost:9999/scene/241/screenshot?t=1730703493"} httpResponse={"bytes":131546,"elapsed":11.842427,"status":200} service=stash
2024-11-04 00:58:20 stash  | 2024-11-04T06:58:20.674546218Z WRN Response: 404 Client Error httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002302","requestMethod":"GET","requestPath":"/scene/241/preview","requestURL":"http://localhost:9999/scene/241/preview"} httpResponse={"bytes":19,"elapsed":2.217044,"status":404} service=stash
2024-11-04 00:58:20 stash  | 2024-11-04T06:58:20.819497539Z WRN Response: 404 Client Error httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002303","requestMethod":"GET","requestPath":"/scene/5b971f2b1a2259b1_thumbs.vtt","requestURL":"http://localhost:9999/scene/5b971f2b1a2259b1_thumbs.vtt"} httpResponse={"bytes":43,"elapsed":1.155529,"status":404} service=stash
2024-11-04 00:58:28 stash  | 2024-11-04T06:58:28.577726542Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002304","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://localhost:9999/graphql"} httpResponse={"bytes":54,"elapsed":1.159239,"status":200} service=stash
2024-11-04 00:58:28 stash  | INFO[2024-11-04 06:58:28] Starting auto-tag of 1 performers, 0 studios, 0 tags 
2024-11-04 00:58:28 stash  | INFO[2024-11-04 06:58:28] Finished auto-tag after 56.727159ms          
2024-11-04 00:58:30 stash  | 2024-11-04T06:58:30.107265094Z INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"###.##.#.#:46108","requestID":"05065a0ba10c/2igG81721z-002305","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://localhost:9999/graphql"} httpResponse={"bytes":160,"elapsed":0.412377,"status":200} service=stash`

**Comment by skier233** [comment]
Do you see any errors in the ai server console? Also what is the current value in the config.py file in the AI Tagger Stash plugin for `API_BASE_URL`?

**Comment by CheezusJeezus** [comment]
No Errors on the AI console. I also did the recommended requirements pip from the console of stash since they weren't properly sharing the python environment. 

My api_base_url is set to the "docker identifier:8000" as setting it to the host machine ip or the attempting to set it to the stash ip seemed to only throw errors

**Comment by skier233** [comment]
I don't think that'd be a valid url. Can you set that to "http://localhost:8000" and if you get errors we can see what the error is.

**Comment by CheezusJeezus** [comment]
Alright so with localhost 8000 I now see this on the stash logs:

`RRO[2024-11-04 23:40:05] [Plugin / AI Tagger] Failed to connect to AI server. Is the AI server running at http://localhost:8000/?   Cannot connect to host localhost:8000 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('::1', 8000, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8000)]`

The command in the documentation spools up two ports, 7483 and 8000. 7483 gives a connection reset, going to localhost:8000 I receive this page.

![image](https://github.com/user-attachments/assets/5ca189ab-fc36-4485-93f6-55e5f0fd9edd)

**Comment by skier233** [comment]
Can you try changing the url in your config.py from "localhost:8000" to "http://0.0.0.0:8000"?

**Comment by skier233** [comment]
Closed as stale. If you're still seeing issue please reopen with additional info.
